/*
 Navicat Premium Data Transfer

 Source Server         : SQLite
 Source Server Type    : SQLite
 Source Server Version : 3017000
 Source Schema         : main

 Target Server Type    : SQLite
 Target Server Version : 3017000
 File Encoding         : 65001

 Date: 29/08/2019 12:48:43
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for backupFieldKey
-- ----------------------------
DROP TABLE IF EXISTS "backupFieldKey";
CREATE TABLE "backupFieldKey" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "tableName" VARCHAR(4000),
  "fieldChosed" varchar(4000),
  "fieldType" text(4000),
  "isSystemDefine" integer,
  "modifier" VARCHAR(4000),
  "modificationTime" integer
);

-- ----------------------------
-- Records of "backupFieldKey"
-- ----------------------------
INSERT INTO "backupFieldKey" VALUES (256, 'TDPF_TASK_INFO', 'C_TASKID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (269, 'TDPF_TASKBUSIPARAMS', 'C_PARAMID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (281, 'TDPF_GLOBAL_PARAMS', 'C_GPARAMID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (282, 'TDPF_TASK_EXENO', 'C_TASKTAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (283, 'TDPF_TASK_EXENO', 'C_PRETASKTAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (284, 'TSYS_TRANS', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (285, 'TSYS_PARAMETER', 'VC_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (286, 'TPARAMETER', 'PARAM_CODE, REL_ORG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (287, 'TSYS_USER_RIGHT', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (288, 'TSYS_USER_RIGHT', 'SUB_TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (289, 'TSYS_USER_RIGHT', 'USER_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (290, 'TSYS_USER_RIGHT', 'BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (291, 'TSYS_USER_RIGHT', 'END_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (292, 'TSYS_USER_RIGHT', 'RIGHT_FLAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (293, 'TSYS_USER', 'USER_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (294, 'TSYS_ROLE', 'ROLE_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (295, 'TSYS_ROLE_RIGHT', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (296, 'TSYS_ROLE_RIGHT', 'SUB_TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (297, 'TSYS_ROLE_RIGHT', 'ROLE_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (298, 'TSYS_ROLE_RIGHT', 'BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (299, 'TSYS_ROLE_RIGHT', 'RIGHT_FLAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (300, 'TSYS_ROLE_RIGHT', 'END_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (301, 'TINDEXSETINDEXS', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (302, 'TINDEXSETINDEXS', 'VC_INDEXS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (303, 'TINDEXSETPARAM', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (304, 'TINDEXSETPARAM', 'VC_PARAM_NAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (305, 'TCONLISTINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (306, 'TMONITORRESULTS', 'L_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (307, 'TMONITORRESULTS', 'L_PORT_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (308, 'TMONITORRESULTS', 'L_RULEID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (309, 'TMONITORRESULTS', 'VC_SCODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (310, 'TREPORTINFO', 'L_REPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (311, 'TREPORTSPECIALPARAM', 'L_REPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (312, 'TREPORTSPECIALPARAM', 'VC_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (313, 'TSUBREPORTS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (314, 'TSUBRTPARAMS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (315, 'TSUBRTPARAMS', 'VC_PARAMNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (316, 'TSUBRTINDEXS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (317, 'TSUBRTINDEXS', 'VC_DISPLAYNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (318, 'TSUBRTINDEXS', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (319, 'TSUBRTINDEXS', 'VC_INDEXS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (320, 'TSQLSELTABLE', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (321, 'TSUBRTINDEXPARAMS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (322, 'TSUBRTINDEXPARAMS', 'C_INDEXGUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (323, 'TSUBRTINDEXPARAMS', 'VC_PARAMNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (324, 'TSSREPORTS', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (325, 'TSSPORTS', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (326, 'TSUBCRIBEINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (327, 'TPORTTREEDATA', 'L_NODE_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (328, 'TDIMDIVIDEDETAIL', 'L_DDETAILSID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (329, 'TDIMINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (330, 'TDIMDIVIDEWAY', 'L_DIVIDEID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (331, 'TBENCHCOMPONENT', 'L_BENCH_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (332, 'TBENCHCOMPONENT', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (333, 'TBENCHCOMPONENT', 'L_BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (334, 'TBENCHMARKINFO', 'L_BENCH_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (335, 'TCUSTOMINDEXINFO', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (336, 'TCUSTOMINDEXPARAMS', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (337, 'TCUSTOMINDEXPARAMS', 'VC_PARA_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (622, 'TDPF_TASK_INFO', 'VC_CUSTOMTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (623, 'TDPF_TASK_INFO', 'C_TASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (624, 'TDPF_TASK_INFO', 'C_UPTASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (625, 'TDPF_TASK_INFO', 'VC_TASKNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (626, 'TDPF_TASK_INFO', 'VC_TASKDLL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (627, 'TDPF_TASK_INFO', 'C_STARTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (628, 'TDPF_TASK_INFO', 'C_EXETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (629, 'TDPF_TASK_INFO', 'L_EXENO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (630, 'TDPF_TASK_INFO', 'C_RUNSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (631, 'TDPF_TASK_INFO', 'L_PROGRESSVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (632, 'TDPF_TASK_INFO', 'VC_TASKEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (633, 'TDPF_TASK_INFO', 'VC_EXETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (634, 'TDPF_TASK_INFO', 'VC_BEGINTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (635, 'TDPF_TASK_INFO', 'VC_ENDTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (636, 'TDPF_TASK_INFO', 'VC_UPEXEDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (637, 'TDPF_TASK_INFO', 'L_TIMEINTERVAL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (638, 'TDPF_TASK_INFO', 'VC_WEEKDAYEXE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (639, 'TDPF_TASK_INFO', 'VC_MONTHWEEKEXE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (640, 'TDPF_TASK_INFO', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (641, 'TDPF_TASK_INFO', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (642, 'TDPF_TASK_INFO', 'VC_TASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (643, 'TDPF_TASKBUSIPARAMS', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (644, 'TDPF_TASKBUSIPARAMS', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (645, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (646, 'TDPF_TASKBUSIPARAMS', 'C_PARAMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (647, 'TDPF_TASKBUSIPARAMS', 'C_TASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (648, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (649, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (650, 'TDPF_TASKBUSIPARAMS', 'C_EDITSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (651, 'TDPF_TASKBUSIPARAMS', 'C_ISENCRYPT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (652, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (653, 'TDPF_TASKBUSIPARAMS', 'L_VALUETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (654, 'TDPF_TASKBUSIPARAMS', 'VC_VALUERANGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (655, 'TDPF_TASK_EXENO', 'C_EXEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (656, 'TDPF_TASK_EXENO', 'C_TASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (657, 'TDPF_TASK_EXENO', 'C_PRETASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (658, 'TDPF_GLOBAL_PARAMS', 'C_GPARAMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (659, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (660, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (661, 'TDPF_GLOBAL_PARAMS', 'C_EDITSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (662, 'TDPF_GLOBAL_PARAMS', 'C_ISENCRYPT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (663, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (664, 'TDPF_GLOBAL_PARAMS', 'L_VALUETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (665, 'TDPF_GLOBAL_PARAMS', 'VC_VALUERANGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (666, 'TDPF_GLOBAL_PARAMS', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (667, 'TDPF_GLOBAL_PARAMS', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (668, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (669, 'TSYS_TRANS', 'TRANS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (670, 'TSYS_TRANS', 'TRANS_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (671, 'TSYS_TRANS', 'KIND_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (672, 'TSYS_TRANS', 'MODEL_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (673, 'TSYS_TRANS', 'REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (674, 'TSYS_TRANS', 'EXT_FIELD_1', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (675, 'TSYS_TRANS', 'EXT_FIELD_2', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (676, 'TSYS_TRANS', 'EXT_FIELD_3', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (677, 'TSYS_PARAMETER', 'PARAM_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (678, 'TSYS_PARAMETER', 'REL_ORG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (679, 'TSYS_PARAMETER', 'KIND_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (680, 'TSYS_PARAMETER', 'PARAM_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (681, 'TSYS_PARAMETER', 'PARAM_VALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (682, 'TSYS_PARAMETER', 'EXT_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (683, 'TSYS_PARAMETER', 'LIFECYCLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (684, 'TSYS_PARAMETER', 'PLATFORM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (685, 'TSYS_PARAMETER', 'PARAM_DESC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (686, 'TSYS_PARAMETER', 'PARAM_REGEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (687, 'TSYS_USER_RIGHT', 'TRANS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (688, 'TSYS_USER_RIGHT', 'SUB_TRANS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (689, 'TSYS_USER_RIGHT', 'USER_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (690, 'TSYS_USER_RIGHT', 'CREATE_BY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (691, 'TSYS_USER_RIGHT', 'CREATE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (692, 'TSYS_USER_RIGHT', 'BEGIN_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (693, 'TSYS_USER_RIGHT', 'END_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (694, 'TSYS_USER_RIGHT', 'RIGHT_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (695, 'TSYS_USER_RIGHT', 'RIGHT_ENABLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (696, 'TSYS_USER', 'VC_RIGHTS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (697, 'TSYS_USER', 'USER_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (698, 'TSYS_USER', 'USER_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (699, 'TSYS_USER', 'USER_PWD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (700, 'TSYS_USER', 'ORG_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (701, 'TSYS_USER', 'USER_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (702, 'TSYS_USER', 'USER_STATUS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (703, 'TSYS_USER', 'LOCK_STATUS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (704, 'TSYS_USER', 'CREATE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (705, 'TSYS_USER', 'MODIFY_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (706, 'TSYS_USER', 'PASS_MODIFY_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (707, 'TSYS_USER', 'MOBILE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (708, 'TSYS_USER', 'EMAIL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (709, 'TSYS_USER', 'EXT_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (710, 'TSYS_USER', 'REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (711, 'TSYS_USER', 'EXT_FIELD_1', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (712, 'TSYS_USER', 'EXT_FIELD_2', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (713, 'TSYS_USER', 'EXT_FIELD_3', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (714, 'TSYS_USER', 'EXT_FIELD_4', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (715, 'TSYS_USER', 'EXT_FIELD_5', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (716, 'TSYS_USER', 'USER_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (717, 'TSYS_USER', 'C_IDENTITYTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (718, 'TSYS_USER', 'C_IDENTITYNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (719, 'TSYS_USER', 'C_CREDENTIALS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (720, 'TSYS_USER', 'CREATE_TIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (721, 'TSYS_USER', 'MODIFY_TIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (722, 'TSYS_USER', 'L_SYNFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (723, 'TSYS_ROLE', 'ROLE_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (724, 'TSYS_ROLE', 'ROLE_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (725, 'TSYS_ROLE', 'CREATOR', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (726, 'TSYS_ROLE', 'REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (727, 'TSYS_ROLE', 'PARENT_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (728, 'TSYS_ROLE', 'ROLE_PATH', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (729, 'TSYS_ROLE', 'ROLE_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (730, 'TSYS_ROLE', 'CREATE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (731, 'TSYS_ROLE', 'MODIFY_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (732, 'TSYS_ROLE', 'CREATE_TIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (733, 'TSYS_ROLE', 'MODIFY_TIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (734, 'TSYS_ROLE_RIGHT', 'TRANS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (735, 'TSYS_ROLE_RIGHT', 'SUB_TRANS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (736, 'TSYS_ROLE_RIGHT', 'ROLE_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (737, 'TSYS_ROLE_RIGHT', 'CREATE_BY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (738, 'TSYS_ROLE_RIGHT', 'CREATE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (739, 'TSYS_ROLE_RIGHT', 'BEGIN_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (740, 'TSYS_ROLE_RIGHT', 'END_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (741, 'TSYS_ROLE_RIGHT', 'RIGHT_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (742, 'TSYS_ROLE_RIGHT', 'RIGHT_ENABLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (743, 'TMONITORRESULTS', 'L_CONTRACTTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (744, 'TMONITORRESULTS', 'L_TREE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (745, 'TMONITORRESULTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (746, 'TMONITORRESULTS', 'L_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (747, 'TMONITORRESULTS', 'L_PORT_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (748, 'TMONITORRESULTS', 'L_RULEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (749, 'TMONITORRESULTS', 'VC_RULEDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (750, 'TMONITORRESULTS', 'L_RULELEVEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (751, 'TMONITORRESULTS', 'L_RULECLASS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (752, 'TMONITORRESULTS', 'VC_RULETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (753, 'TMONITORRESULTS', 'L_INDEXTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (754, 'TMONITORRESULTS', 'L_THTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (755, 'TMONITORRESULTS', 'L_THUNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (756, 'TMONITORRESULTS', 'VC_NORMALMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (757, 'TMONITORRESULTS', 'VC_NORMALMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (758, 'TMONITORRESULTS', 'VC_PREALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (759, 'TMONITORRESULTS', 'VC_PREALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (760, 'TMONITORRESULTS', 'VC_ALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (761, 'TMONITORRESULTS', 'VC_ALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (762, 'TMONITORRESULTS', 'VC_SCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (763, 'TMONITORRESULTS', 'VC_SNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (764, 'TMONITORRESULTS', 'VC_CLASSDIM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (765, 'TMONITORRESULTS', 'VC_DIMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (766, 'TMONITORRESULTS', 'VC_MONITORRESULT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (767, 'TMONITORRESULTS', 'L_ALERTTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (768, 'TMONITORRESULTS', 'VC_MOLEVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (769, 'TMONITORRESULTS', 'VC_DENOVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (770, 'TMONITORRESULTS', 'VC_VALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (771, 'TMONITORRESULTS', 'VC_OFFVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (772, 'TMONITORRESULTS', 'L_CHECKFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (773, 'TMONITORRESULTS', 'VC_CHECKMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (774, 'TMONITORRESULTS', 'D_CHECKDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (775, 'TMONITORRESULTS', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (776, 'TMONITORRESULTS', 'VC_SENDUSER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (777, 'TMONITORRESULTS', 'VC_TONAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (778, 'TMONITORRESULTS', 'L_SENDFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (779, 'TMONITORRESULTS', 'L_ALERT_TIMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (780, 'TMONITORRESULTS', 'C_LEVEL_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (781, 'TMONITORRESULTS', 'D_SENDDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (782, 'TMONITORRESULTS', 'L_OPTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (783, 'TMONITORRESULTS', 'VC_OPTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (784, 'TMONITORRESULTS', 'L_CONTRACT_TIMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (785, 'TMONITORRESULTS', 'VC_CHECKRESULT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (786, 'TMONITORRESULTS', 'VC_OPTMEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (787, 'TMONITORRESULTS', 'L_OPENPOSITION_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (788, 'TMONITORRESULTS', 'L_MINALERT_TIMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (789, 'TMONITORRESULTS', 'VC_MAIL_CHECKMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (790, 'TMONITORRESULTS', 'D_MAIL_CHECKDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (791, 'TMONITORRESULTS', 'VC_MAIL_CHECKRESULT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (792, 'TMONITORRULES', 'C_REALTIMEMONITOR', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (793, 'TMONITORRULES', 'VC_DENOIDX_CONEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (794, 'TMONITORRULES', 'C_DENOIDX_CONEXPS_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (795, 'TMONITORRULES', 'L_CONTRACT_TIMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (796, 'TMONITORRULES', 'L_PORT_DIMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (797, 'TMONITORRULES', 'L_ISCOMPLEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (798, 'TMONITORRULES', 'L_ALLIANCE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (799, 'TMONITORRULES', 'L_ABSFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (800, 'TMONITORRULES', 'L_MONITORPOSITION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (801, 'TMONITORRULES', 'L_MONITORWIND', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (802, 'TMONITORRULES', 'L_ALERTSHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (803, 'TMONITORRULES', 'L_RULEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (804, 'TMONITORRULES', 'VC_RULECODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (805, 'TMONITORRULES', 'VC_RULEDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (806, 'TMONITORRULES', 'L_RULELEVEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (807, 'TMONITORRULES', 'VC_RULEFROM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (808, 'TMONITORRULES', 'L_BDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (809, 'TMONITORRULES', 'L_EDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (810, 'TMONITORRULES', 'L_ACCCONTROL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (811, 'TMONITORRULES', 'L_ACCCLASSSTYLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (812, 'TMONITORRULES', 'L_SECUCONTROL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (813, 'TMONITORRULES', 'L_DIMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (814, 'TMONITORRULES', 'VC_RULETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (815, 'TMONITORRULES', 'L_INDEXTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (816, 'TMONITORRULES', 'VC_MOLEIDXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (817, 'TMONITORRULES', 'VC_DENOIDXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (818, 'TMONITORRULES', 'VC_MOLEIDXPARAMS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (819, 'TMONITORRULES', 'VC_DENOIDXPARAMS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (820, 'TMONITORRULES', 'L_THTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (821, 'TMONITORRULES', 'L_THUNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (822, 'TMONITORRULES', 'VC_NORMALMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (823, 'TMONITORRULES', 'VC_NORMALMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (824, 'TMONITORRULES', 'VC_PREALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (825, 'TMONITORRULES', 'VC_PREALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (826, 'TMONITORRULES', 'VC_ALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (827, 'TMONITORRULES', 'VC_ALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (828, 'TMONITORRULES', 'L_OPTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (829, 'TMONITORRULES', 'VC_OPTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (830, 'TMONITORRULES', 'D_OPTDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (831, 'TMONITORRULES', 'L_CHECKFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (832, 'TMONITORRULES', 'VC_CHECKMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (833, 'TMONITORRULES', 'D_CHECKDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (834, 'TMONITORRULES', 'VC_EXRULECODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (835, 'TMONITORRULES', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (836, 'TMONITORRULES', 'VC_FUNCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (837, 'TMONITORRULES', 'L_RESULTPRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (838, 'TMONITORRULES', 'C_CURRENTGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (839, 'TMONITORRULES', 'L_REPODETAIL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (840, 'TMONITORRULES', 'L_PORT_BIGKIND', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (841, 'TMONITORRULES', 'VC_CHAPTER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (842, 'TMONITORRULESCURRENTS', 'L_RULELEVEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (843, 'TMONITORRULESCURRENTS', 'VC_RULEFROM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (844, 'TMONITORRULESCURRENTS', 'L_BDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (845, 'TMONITORRULESCURRENTS', 'L_EDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (846, 'TMONITORRULESCURRENTS', 'L_ACCCONTROL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (847, 'TMONITORRULESCURRENTS', 'L_ACCCLASSSTYLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (848, 'TMONITORRULESCURRENTS', 'L_SECUCONTROL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (849, 'TMONITORRULESCURRENTS', 'L_DIMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (850, 'TMONITORRULESCURRENTS', 'VC_RULETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (851, 'TMONITORRULESCURRENTS', 'L_INDEXTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (852, 'TMONITORRULESCURRENTS', 'VC_MOLEIDXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (853, 'TMONITORRULESCURRENTS', 'VC_DENOIDXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (854, 'TMONITORRULESCURRENTS', 'VC_MOLEIDXPARAMS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (855, 'TMONITORRULESCURRENTS', 'VC_DENOIDXPARAMS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (856, 'TMONITORRULESCURRENTS', 'L_THTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (857, 'TMONITORRULESCURRENTS', 'L_THUNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (858, 'TMONITORRULESCURRENTS', 'VC_NORMALMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (859, 'TMONITORRULESCURRENTS', 'VC_NORMALMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (860, 'TMONITORRULESCURRENTS', 'VC_PREALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (861, 'TMONITORRULESCURRENTS', 'VC_PREALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (862, 'TMONITORRULESCURRENTS', 'VC_ALERTMAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (863, 'TMONITORRULESCURRENTS', 'VC_ALERTMINVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (864, 'TMONITORRULESCURRENTS', 'L_OPTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (865, 'TMONITORRULESCURRENTS', 'VC_OPTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (866, 'TMONITORRULESCURRENTS', 'D_OPTDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (867, 'TMONITORRULESCURRENTS', 'L_CHECKFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (868, 'TMONITORRULESCURRENTS', 'VC_CHECKMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (869, 'TMONITORRULESCURRENTS', 'D_CHECKDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (870, 'TMONITORRULESCURRENTS', 'VC_EXRULECODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (871, 'TMONITORRULESCURRENTS', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (872, 'TMONITORRULESCURRENTS', 'VC_FUNCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (873, 'TMONITORRULESCURRENTS', 'C_STATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (874, 'TMONITORRULESCURRENTS', 'L_RESULTPRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (875, 'TMONITORRULESCURRENTS', 'L_REPODETAIL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (876, 'TMONITORRULESCURRENTS', 'L_PORT_BIGKIND', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (877, 'TMONITORRULESCURRENTS', 'VC_CHAPTER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (878, 'TMONITORRULESCURRENTS', 'C_REALTIMEMONITOR', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (879, 'TMONITORRULESCURRENTS', 'VC_DENOIDX_CONEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (880, 'TMONITORRULESCURRENTS', 'C_DENOIDX_CONEXPS_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (881, 'TMONITORRULESCURRENTS', 'L_CONTRACT_TIMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (882, 'TMONITORRULESCURRENTS', 'L_PORT_DIMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (883, 'TMONITORRULESCURRENTS', 'L_ISCOMPLEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (884, 'TMONITORRULESCURRENTS', 'L_ALLIANCE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (885, 'TMONITORRULESCURRENTS', 'VC_SOURCE_RULECODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (886, 'TMONITORRULESCURRENTS', 'L_ABSFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (887, 'TMONITORRULESCURRENTS', 'L_MONITORPOSITION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (888, 'TMONITORRULESCURRENTS', 'L_MONITORWIND', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (889, 'TMONITORRULESCURRENTS', 'L_ALERTSHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (890, 'TMONITORRULESCURRENTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (891, 'TMONITORRULESCURRENTS', 'L_RULEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (892, 'TMONITORRULESCURRENTS', 'VC_RULECODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (893, 'TMONITORRULESCURRENTS', 'VC_RULEDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (894, 'TMONITORRULEACCVALUESCURRENTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (895, 'TMONITORRULEACCVALUESCURRENTS', 'C_MONITORRULEGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (896, 'TMONITORRULEACCVALUESCURRENTS', 'L_RULEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (897, 'TMONITORRULEACCVALUESCURRENTS', 'VC_ACCCLASSVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (898, 'TMONITORRULEACCVALUESCURRENTS', 'L_ACCCLASSSTYLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (899, 'TREPORTINFO', 'L_CALC_PORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (900, 'TREPORTINFO', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (901, 'TREPORTINFO', 'VC_REPORTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (902, 'TREPORTINFO', 'VC_REPORTDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (903, 'TREPORTINFO', 'C_REPORTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (904, 'TREPORTINFO', 'VC_CREATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (905, 'TREPORTINFO', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (906, 'TREPORTINFO', 'VC_CHECKCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (907, 'TREPORTINFO', 'L_DATEFREQUENCY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (908, 'TREPORTINFO', 'L_SHOWPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (909, 'TREPORTINFO', 'L_SHOWBECHE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (910, 'TREPORTINFO', 'L_SHOWBENCH', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (911, 'TREPORTINFO', 'L_REPORT_TEMPLET', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (912, 'TREPORTINFO', 'VC_REPORT_CNTDEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (913, 'TREPORTINFO', 'VC_EXPORT_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (914, 'TREPORTRESULTS', 'VC_USERNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (915, 'TREPORTRESULTS', 'C_CALCGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (916, 'TREPORTRESULTS', 'VC_PORT_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (917, 'TREPORTRESULTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (918, 'TREPORTRESULTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (919, 'TREPORTRESULTS', 'VC_PORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (920, 'TREPORTRESULTS', 'VC_DEFNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (921, 'TREPORTRESULTS', 'VC_REPORTDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (922, 'TREPORTRESULTS', 'VC_CONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (923, 'TREPORTRESULTS', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (924, 'TREPORTRESULTS', 'L_GENFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (925, 'TREPORTRESULTS', 'L_REPORT_TEMPLET', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (926, 'TREPORTRESULTS', 'C_SUBSCRIBE_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (927, 'TREPORTRESULTS', 'VC_TRANSPARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (928, 'TREPORTRESULTS', 'VC_SELCONS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (929, 'TREPORTRESULTS', 'VC_HASHCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (930, 'TREPORTSPECIALPARAM', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (931, 'TREPORTSPECIALPARAM', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (932, 'TREPORTSPECIALPARAM', 'VC_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (933, 'TREPORTSPECIALPARAM', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (934, 'TREPORTSPECIALPARAM', 'VC_DEFAULTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (935, 'TREPORTSPECIALPARAM', 'VC_FIELDCONFIG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (936, 'TREPORTSPECIALPARAM', 'VC_XTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (937, 'TREPORTSPECIALPARAM', 'L_DICTNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (938, 'TREPORTSPECIALPARAM', 'VC_CONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (939, 'TREPORTSPECIALPARAM', 'VC_UNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (940, 'TREPORTSPECIALPARAM', 'L_ALLOWBLANK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (941, 'TREPORTSPECIALPARAM', 'L_SHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (942, 'TREPORTSPECIALPARAM', 'L_MULTIPLE_SELECT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (943, 'TREPORTSPECIALPARAM', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (944, 'TSUBREPORTS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (945, 'TSUBREPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (946, 'TSUBREPORTS', 'VC_SUBREPORTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (947, 'TSUBREPORTS', 'VC_SUBREPORTENNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (948, 'TSUBREPORTS', 'VC_SUBREPORTDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (949, 'TSUBREPORTS', 'L_DATEFREQUENCY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (950, 'TSUBREPORTS', 'L_SUBREPORTWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (951, 'TSUBREPORTS', 'VC_SQLGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (952, 'TSUBREPORTS', 'L_SUBREPORTNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (953, 'TSUBREPORTS', 'VC_DIMGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (954, 'TSUBREPORTS', 'L_ACTIVE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (955, 'TSUBREPORTS', 'L_MAPTYPE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (956, 'TSUBREPORTS', 'VC_DEFINESQL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (957, 'TSUBREPORTS', 'L_SQLTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (958, 'TSUBRTPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (959, 'TSUBRTPARAMS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (960, 'TSUBRTPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (961, 'TSUBRTPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (962, 'TSUBRTINDEXS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (963, 'TSUBRTINDEXS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (964, 'TSUBRTINDEXS', 'L_INDEXNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (965, 'TSUBRTINDEXS', 'VC_DISPLAYNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (966, 'TSUBRTINDEXS', 'L_INDEXSEQ', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (967, 'TSUBRTINDEXS', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (968, 'TSUBRTINDEXS', 'VC_INDEXS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (969, 'TSQLSELTABLE', 'VC_SQLCNTEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (970, 'TSQLSELTABLE', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (971, 'TSQLSELTABLE', 'VC_SQLNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (972, 'TSQLSELTABLE', 'VC_SQLCNT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (973, 'TSQLSELTABLE', 'VC_SQLDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (974, 'TSQLSELTABLE', 'L_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (975, 'TSQLSELTABLE', 'L_CALCWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (976, 'TSQLSELTABLE', 'VC_FUNCNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (977, 'TSQLSELTABLE', 'L_MANCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (978, 'TSUBRTINDEXPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (979, 'TSUBRTINDEXPARAMS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (980, 'TSUBRTINDEXPARAMS', 'C_INDEXGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (981, 'TSUBRTINDEXPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (982, 'TSUBRTINDEXPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (983, 'TSSREPORTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (984, 'TSSREPORTS', 'C_SSGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (985, 'TSSREPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (986, 'TSSREPORTS', 'VC_TRANSPARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (987, 'TSSPORTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (988, 'TSSPORTS', 'C_SSGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (989, 'TSSPORTS', 'L_PORTTREE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (990, 'TSSPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (991, 'TSUBCRIBEINFO', 'C_REMOVEDELISTPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (992, 'TSUBCRIBEINFO', 'VC_MAILTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (993, 'TSUBCRIBEINFO', 'VC_FILENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (994, 'TSUBCRIBEINFO', 'VC_CCMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (995, 'TSUBCRIBEINFO', 'ISFTPUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (996, 'TSUBCRIBEINFO', 'L_EDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (997, 'TSUBCRIBEINFO', 'DATEFROM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (998, 'TSUBCRIBEINFO', 'ISCALCHIS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (999, 'TSUBCRIBEINFO', 'VC_TASKNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1000, 'TSUBCRIBEINFO', 'REPCONCURRENCE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1001, 'TSUBCRIBEINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1002, 'TSUBCRIBEINFO', 'VC_RECMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1003, 'TSUBCRIBEINFO', 'C_RECGROUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1004, 'TSUBCRIBEINFO', 'C_ISRECGROUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1005, 'TSUBCRIBEINFO', 'L_CALCDUR', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1006, 'TSUBCRIBEINFO', 'D_UPCALCDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1007, 'TSUBCRIBEINFO', 'C_ONOFF', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1008, 'TSUBCRIBEINFO', 'C_SENDMAIL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1009, 'TSUBCRIBEINFO', 'L_RFILEFORMAT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1010, 'TSUBCRIBEINFO', 'VC_RBEGINDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1011, 'TSUBCRIBEINFO', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1012, 'TSUBCRIBEINFO', 'VC_MONIFYMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1013, 'TSUBCRIBEINFO', 'D_MONIFYTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1014, 'TSUBCRIBEINFO', 'VC_CREATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1015, 'TSUBCRIBEINFO', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1016, 'TSUBCRIBEINFO', 'VC_MAILTITLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1017, 'TSUBCRIBEINFO', 'VC_MAILCONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1018, 'TSUBCRIBEINFO', 'L_PRIORITY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1019, 'TSUBCRIBEINFO', 'L_DATETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1020, 'TSUBCRIBEINFO', 'L_DELAYDAYS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1021, 'TSUBCRIBEINFO', 'L_EXPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1022, 'TSUBCRIBEINFO', 'SENDREPORTTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1023, 'TSUBCRIBEINFO', 'ISPACK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1024, 'TSUBCRIBEINFO', 'VC_TRIGGERTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1025, 'TSUBCRIBEINFO', 'D_LASTTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1026, 'TSUBCRIBEINFO', 'ISREMINDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1027, 'TPORTTREEDATA', 'L_PEER_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1028, 'TPORTTREEDATA', 'L_NODE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1029, 'TPORTTREEDATA', 'VC_NODE_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1030, 'TPORTTREEDATA', 'L_PARENT_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1031, 'TPORTTREEDATA', 'L_CASHFLOW_STRATEGY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1032, 'TPORTTREEDATA', 'L_DIVIDEND_STRATEGY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1033, 'TPORTTREEDATA', 'L_TREE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1034, 'TPORTTREEDATA', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1035, 'TPORTTREEDATA', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1036, 'TPORTTREEDATA', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1037, 'TPORTTREEDATA', 'VC_NODE_ALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1038, 'TPORTTREEDATA', 'L_CREATE_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1039, 'TPORTTREEDATA', 'L_MARKET_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1040, 'TPORTTREEDATA', 'L_INNER_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1041, 'TPORTTREEDATA', 'L_DEPART_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1042, 'TPORTTREEDATA', 'C_DIM_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1043, 'TPORTTREEDATA', 'VC_PEER_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1044, 'TDIMDIVIDEDETAIL', 'L_DDETAILSID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1045, 'TDIMDIVIDEDETAIL', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1046, 'TDIMDIVIDEDETAIL', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1047, 'TDIMDIVIDEDETAIL', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1048, 'TDIMDIVIDEDETAIL', 'VC_DIMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1049, 'TDIMDIVIDEDETAIL', 'VC_CALCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1050, 'TDIMDIVIDEDETAIL', 'VC_FUNCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1051, 'TDIMDIVIDEDETAIL', 'VC_DESC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1052, 'TDIMINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1053, 'TDIMINFO', 'C_PGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1054, 'TDIMINFO', 'L_DIMTREEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1055, 'TDIMINFO', 'VC_DIMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1056, 'TDIMINFO', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1057, 'TDIMINFO', 'VC_DIVIDENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1058, 'TDIMINFO', 'L_DDETAILSID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1059, 'TDIMINFO', 'L_LEVEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1060, 'TDIMINFO', 'L_SHOWWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1061, 'TDIMINFO', 'L_READONLY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1062, 'TDIMINFO', 'L_CLASS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1063, 'TDIMINFO', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1064, 'TDIMINFO', 'L_DIMCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1065, 'TDIMINFO', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1066, 'TDIMINFO', 'VC_FUNCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1067, 'TDIMDIVIDEWAY', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1068, 'TDIMDIVIDEWAY', 'VC_DIMDIVIDENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1069, 'TDIMDIVIDEWAY', 'L_DIVIDETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1070, 'TDIMDIVIDEWAY', 'L_DIMFUNCID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1071, 'TDIMDIVIDEWAY', 'L_READONLY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1072, 'TDIMDIVIDEWAY', 'L_CLASS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1073, 'TDIMDIVIDEWAY', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1074, 'TDIMDIVIDEWAY', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1075, 'TDIMDIVIDEWAY', 'L_DIMCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1076, 'TBENCHCOMPONENT', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1077, 'TBENCHCOMPONENT', 'L_BENCH_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1078, 'TBENCHCOMPONENT', 'L_DIM_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1079, 'TBENCHCOMPONENT', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1080, 'TBENCHCOMPONENT', 'L_BEGIN_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1081, 'TBENCHCOMPONENT', 'EN_WEIGHT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1082, 'TBENCHCOMPONENT', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1083, 'TBENCHCOMPONENT', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1084, 'TBENCHMARKINFO', 'RATEADD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1085, 'TBENCHMARKINFO', 'RATEADDCALCWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1086, 'TBENCHMARKINFO', 'L_BENCH_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1087, 'TBENCHMARKINFO', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1088, 'TBENCHMARKINFO', 'VC_CALCWEIGHT_WAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1089, 'TBENCHMARKINFO', 'VC_ACCUMULATE_WAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1090, 'TBENCHMARKINFO', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1091, 'TBENCHMARKINFO', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1092, 'TBENCHMARKINFO', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1093, 'TBENCHMARKINFO', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1094, 'TBENCHMARKINFO', 'C_CATEGORY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1095, 'TCUSTOMINDEXINFO', 'L_ISSYS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1096, 'TCUSTOMINDEXINFO', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1097, 'TCUSTOMINDEXINFO', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1098, 'TCUSTOMINDEXINFO', 'C_NIGHT_CALC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1099, 'TCUSTOMINDEXINFO', 'VC_INDEX_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1100, 'TCUSTOMINDEXINFO', 'L_SAMPWEIGHT_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1101, 'TCUSTOMINDEXINFO', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1102, 'TCUSTOMINDEXINFO', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1103, 'TCUSTOMINDEXINFO', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1104, 'TCUSTOMINDEXPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1105, 'TCUSTOMINDEXPARAMS', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1106, 'TCUSTOMINDEXPARAMS', 'VC_PARA_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1107, 'TCUSTOMINDEXPARAMS', 'VC_PARA_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1108, 'TCUSTOMINDEXPARAMS', 'VC_PARA_VALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1109, 'TCUSTOMINDEXPARAMS', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1110, 'TCUSTOMINDEXPARAMS', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1111, 'TCUSTOMINTEREST', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1112, 'TCUSTOMINTEREST', 'L_INTEREST_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1113, 'TCUSTOMINTEREST', 'L_BEGIN_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1114, 'TCUSTOMINTEREST', 'EN_INTERESTRATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1115, 'TCUSTOMINTEREST', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1116, 'TCUSTOMINTEREST', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1117, 'TCUSTOMINTERESTINFO', 'L_INTEREST_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1118, 'TCUSTOMINTERESTINFO', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1119, 'TCUSTOMINTERESTINFO', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1120, 'TCUSTOMINTERESTINFO', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1121, 'TCUSTOMINTERESTINFO', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1122, 'TINDEXSETINDEXS', 'C_ISADDBENCHHOLD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1123, 'TINDEXSETINDEXS', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1124, 'TINDEXSETINDEXS', 'VC_INDEXS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1125, 'TINDEXSETINDEXS', 'VC_INDEXS_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1126, 'TINDEXSETINDEXS', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1127, 'TINDEXSETINDEXS', 'L_INDEXS_DIM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1128, 'TINDEXSETINDEXS', 'L_INDEXS_AGGREGATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1129, 'TINDEXSETINDEXS', 'VC_WEIGHT_FIELD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1130, 'TINDEXSETINDEXS', 'L_INDEXVALUE_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1131, 'TINDEXSETINDEXS', 'L_INDEXS_EXTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1132, 'TINDEXSETINDEXS', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1133, 'TINDEXSETINDEXS', 'L_MODULE_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1134, 'TINDEXSETINDEXS', 'L_INDEXVALUELEN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1135, 'TINDEXSETINDEXS', 'VC_ISSHOW_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1136, 'TINDEXSETINDEXS', 'L_RESULTUNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1137, 'TINDEXSETINDEXS', 'L_RESULTPRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1138, 'TINDEXSETINDEXS', 'L_IS_STORAGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1139, 'TINDEXSETINDEXS', 'VC_DEFAULTSHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1140, 'TINDEXSETINDEXS', 'VC_INDEX_PARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1141, 'TINDEXSETINDEXS', 'VC_INDEX_VIEWPARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1142, 'TINDEXSETINDEXS', 'VC_DEFAULTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1143, 'TINDEXSETINDEXS', 'RISK_FUNCTION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1144, 'TINDEXSETPARAM', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1145, 'TINDEXSETPARAM', 'VC_PARAM_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1146, 'TINDEXSETPARAM', 'VC_PARAM_CHNNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1147, 'TINDEXSETPARAM', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1148, 'TINDEXSETPARAM', 'VC_PARAM_DEAFTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1149, 'TINDEXSETPARAM', 'L_UNIT_INDEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1150, 'TINDEXSETPARAM', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1151, 'TINDEXSETPARAM', 'VC_XTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1152, 'TINDEXSETPARAM', 'VC_CONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1153, 'TINDEXSETPARAM', 'VC_UNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1154, 'TINDEXSETPARAM', 'VC_MIXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1155, 'TINDEXSETPARAM', 'VC_MAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1156, 'TINDEXSETPARAM', 'L_PRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1157, 'TINDEXSETPARAM', 'VC_PARAMDYNAMIC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1158, 'TCONLISTINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1159, 'TCONLISTINFO', 'C_CONGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1160, 'TCONLISTINFO', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1161, 'TCONLISTINFO', 'VC_INDEXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1162, 'TCONLISTINFO', 'L_RELATIONEXP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1163, 'TCONLISTINFO', 'VC_INDEXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1164, 'TCONLISTINFO', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1165, 'TCONLISTINFO', 'VC_INDEXVALUENAMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1166, 'TCONLISTINFO', 'VC_PARAMVALUENAMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1167, 'TCONLISTINFO', 'VC_GROUPGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1168, 'TCONLISTINFO', 'L_CONTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1169, 'TSUBFUNCUSTOMVIEW', 'L_SUBVIEWWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1170, 'TSUBFUNCUSTOMVIEW', 'VC_DEFINESQL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1171, 'TSUBFUNCUSTOMVIEW', 'L_SQLTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1172, 'TSUBFUNCUSTOMVIEW', 'VC_SQLGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1173, 'TSUBFUNCUSTOMVIEW', 'L_FRCPID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1174, 'TSUBFUNCUSTOMVIEW', 'C_SUBVIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1175, 'TSUBFUNCUSTOMVIEW', 'C_VIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1176, 'TSUBFUNCUSTOMVIEW', 'VC_SUBVIEWNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1177, 'TSUBFUNCUSTOMVIEW', 'VC_SUBVIEWDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1178, 'TSUBFUNCUSTOMVIEW', 'L_DATEFREQUENCY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1179, 'TSUBFUNCUSTOMVIEW', 'L_SUBVIEWNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1180, 'TSUBFUNCUSTOMVIEW', 'VC_DIMGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1181, 'TSUBFUNCUSTOMVIEW', 'VC_TABLENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1182, 'TSUBFUNCUSTOMVIEW', 'VC_SUBVIEWENNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1183, 'TSUBFCVWPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1184, 'TSUBFCVWPARAMS', 'C_SUBVIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1185, 'TSUBFCVWPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1186, 'TSUBFCVWPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1187, 'TSUBFCVWINDEXS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1188, 'TSUBFCVWINDEXS', 'C_SUBVIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1189, 'TSUBFCVWINDEXS', 'L_INDEXNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1190, 'TSUBFCVWINDEXS', 'VC_DISPLAYNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1191, 'TSUBFCVWINDEXS', 'L_INDEXSEQ', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1192, 'TSUBFCVWINDEXS', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1193, 'TSUBFCVWINDEXS', 'VC_INDEXS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1194, 'TSUBFCVWINDEXS', 'L_INDEX_INDEXES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1195, 'TFUNCUSTOMVIEW', 'C_CALCMODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1196, 'TFUNCUSTOMVIEW', 'C_VIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1197, 'TFUNCUSTOMVIEW', 'VC_VIEWNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1198, 'TFUNCUSTOMVIEW', 'VC_VIEWDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1199, 'TFUNCUSTOMVIEW', 'C_CLASSTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1200, 'TFUNCUSTOMVIEW', 'VC_CREATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1201, 'TFUNCUSTOMVIEW', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1202, 'TFUNCUSTOMVIEW', 'L_MODELID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1203, 'TFUNCUSTOMVIEW', 'C_CONFIGURED', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1204, 'TFUNCUSTOMVIEW', 'VC_SHOWTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1205, 'TFUNCUSTOMVIEW', 'VC_SHOWBEN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1206, 'TFUNCUSTOMVIEW', 'L_ISPUBLISH', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1207, 'TFUNCUSTOMVIEW', 'L_LOAD_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1208, 'TFUNCUSTOMVIEW', 'VC_SHOWPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1209, 'TSUBFCVWREGIONINDEXS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1210, 'TSUBFCVWREGIONINDEXS', 'C_REGIONID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1211, 'TSUBFCVWREGIONINDEXS', 'C_INDEXGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1212, 'TSUBFCVWREGIONINDEXS', 'L_ISCHARTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1213, 'TSUBFCVWREGIONINDEXS', 'VC_FORMAT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1214, 'TSUBFCVWREGIONINDEXS', 'L_ALGIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1215, 'TSUBFCVWREGIONINDEXS', 'L_DATATYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1216, 'TSUBFCVWREGIONINDEXS', 'C_YTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1217, 'TSUBFCVWREGION', 'L_STACKED', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1218, 'TSUBFCVWREGION', 'VC_YLEFT_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1219, 'TSUBFCVWREGION', 'VC_YRIGHT_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1220, 'TSUBFCVWREGION', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1221, 'TSUBFCVWREGION', 'C_VIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1222, 'TSUBFCVWREGION', 'C_SUBVIEWID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1223, 'TSUBFCVWREGION', 'L_POSITION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1224, 'TSUBFCVWREGION', 'L_MODELFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1225, 'TSUBFCVWREGION', 'VC_CHARTLABEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (1226, 'TSUBFCVWREGION', 'VC_PICNAME', 1, 1, NULL, NULL);

-- ----------------------------
-- Table structure for backupInformation
-- ----------------------------
DROP TABLE IF EXISTS "backupInformation";
CREATE TABLE "backupInformation" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "backupVersion" integer,
  "backupTime" text,
  "beginTime" integer,
  "endTime" integer,
  "hasContrast" integer
);

-- ----------------------------
-- Records of "backupInformation"
-- ----------------------------
INSERT INTO "backupInformation" VALUES (5, 1, '2019-08-29 10:26:28', 20140101, 20190801, 0);
INSERT INTO "backupInformation" VALUES (6, 2, '2019-08-29 11:17:51', 20140801, 20190801, 0);
INSERT INTO "backupInformation" VALUES (7, 3, '2019-08-29 11:37:53', 20140101, 20190801, 1);

-- ----------------------------
-- Table structure for backupObjectNameList
-- ----------------------------
DROP TABLE IF EXISTS "backupObjectNameList";
CREATE TABLE "backupObjectNameList" (
  "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "backupVersion" INTEGER,
  "objectName" text(4000),
  "backupObjectName" integer(4000),
  "ObjectType" INTEGER
);

-- ----------------------------
-- Records of "backupObjectNameList"
-- ----------------------------
INSERT INTO "backupObjectNameList" VALUES (139, 1, 'TCONLISTINFO', 1, 1);
INSERT INTO "backupObjectNameList" VALUES (140, 1, 'TDIMDIVIDEDETAIL', 2, 1);
INSERT INTO "backupObjectNameList" VALUES (141, 1, 'TDIMDIVIDEWAY', 3, 1);
INSERT INTO "backupObjectNameList" VALUES (142, 1, 'TDIMINFO', 4, 1);
INSERT INTO "backupObjectNameList" VALUES (143, 1, 'TDPF_GLOBAL_PARAMS', 5, 1);
INSERT INTO "backupObjectNameList" VALUES (144, 1, 'TDPF_TASKBUSIPARAMS', 6, 1);
INSERT INTO "backupObjectNameList" VALUES (145, 1, 'TDPF_TASK_EXENO', 7, 1);
INSERT INTO "backupObjectNameList" VALUES (146, 1, 'TDPF_TASK_INFO', 8, 1);
INSERT INTO "backupObjectNameList" VALUES (147, 1, 'TMONITORRESULTS', 9, 1);
INSERT INTO "backupObjectNameList" VALUES (148, 1, 'TMONITORRULEACCVALUESCURRENTS', 10, 1);
INSERT INTO "backupObjectNameList" VALUES (149, 1, 'TMONITORRULES', 11, 1);
INSERT INTO "backupObjectNameList" VALUES (150, 1, 'TMONITORRULESCURRENTS', 12, 1);
INSERT INTO "backupObjectNameList" VALUES (151, 1, 'TPORTTREEDATA', 13, 1);
INSERT INTO "backupObjectNameList" VALUES (152, 1, 'TREPORTINFO', 14, 1);
INSERT INTO "backupObjectNameList" VALUES (153, 1, 'TREPORTRESULTS', 15, 1);
INSERT INTO "backupObjectNameList" VALUES (154, 1, 'TREPORTSPECIALPARAM', 16, 1);
INSERT INTO "backupObjectNameList" VALUES (155, 1, 'TSQLSELTABLE', 17, 1);
INSERT INTO "backupObjectNameList" VALUES (156, 1, 'TSSPORTS', 18, 1);
INSERT INTO "backupObjectNameList" VALUES (157, 1, 'TSSREPORTS', 19, 1);
INSERT INTO "backupObjectNameList" VALUES (158, 1, 'TSUBCRIBEINFO', 20, 1);
INSERT INTO "backupObjectNameList" VALUES (159, 1, 'TSUBREPORTS', 21, 1);
INSERT INTO "backupObjectNameList" VALUES (160, 1, 'TSUBRTINDEXPARAMS', 22, 1);
INSERT INTO "backupObjectNameList" VALUES (161, 1, 'TSUBRTINDEXS', 23, 1);
INSERT INTO "backupObjectNameList" VALUES (162, 1, 'TSUBRTPARAMS', 24, 1);
INSERT INTO "backupObjectNameList" VALUES (163, 1, 'TSYS_ROLE', 25, 1);
INSERT INTO "backupObjectNameList" VALUES (164, 1, 'TSYS_ROLE_RIGHT', 26, 1);
INSERT INTO "backupObjectNameList" VALUES (165, 1, 'TSYS_TRANS', 27, 1);
INSERT INTO "backupObjectNameList" VALUES (166, 1, 'TSYS_USER', 28, 1);
INSERT INTO "backupObjectNameList" VALUES (167, 1, 'TSYS_USER_RIGHT', 29, 1);
INSERT INTO "backupObjectNameList" VALUES (168, 1, 'TINDEXSETINDEXS', 30, 1);
INSERT INTO "backupObjectNameList" VALUES (169, 1, 'TINDEXSETPARAM', 31, 1);
INSERT INTO "backupObjectNameList" VALUES (170, 1, 'TSYS_PARAMETER', 32, 1);
INSERT INTO "backupObjectNameList" VALUES (171, 2, 'TDPF_GLOBAL_PARAMS', 33, 1);
INSERT INTO "backupObjectNameList" VALUES (172, 2, 'TDPF_TASKBUSIPARAMS', 34, 1);
INSERT INTO "backupObjectNameList" VALUES (173, 2, 'TDPF_TASK_EXENO', 35, 1);
INSERT INTO "backupObjectNameList" VALUES (174, 2, 'TDPF_TASK_INFO', 36, 1);
INSERT INTO "backupObjectNameList" VALUES (175, 3, 'TDPF_GLOBAL_PARAMS', 37, 1);
INSERT INTO "backupObjectNameList" VALUES (176, 3, 'TDPF_TASKBUSIPARAMS', 38, 1);
INSERT INTO "backupObjectNameList" VALUES (177, 3, 'TDPF_TASK_EXENO', 39, 1);
INSERT INTO "backupObjectNameList" VALUES (178, 3, 'TDPF_TASK_INFO', 40, 1);

-- ----------------------------
-- Table structure for functionQuotaList
-- ----------------------------
DROP TABLE IF EXISTS "functionQuotaList";
CREATE TABLE "functionQuotaList" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "functionQuotaName" VARCHAR(4000),
  "functionQuotaType" INTEGER
);

-- ----------------------------
-- Records of "functionQuotaList"
-- ----------------------------
INSERT INTO "functionQuotaList" VALUES (1, '功能1', 1);
INSERT INTO "functionQuotaList" VALUES (2, '功能2', 1);
INSERT INTO "functionQuotaList" VALUES (3, '指标1', 2);

-- ----------------------------
-- Table structure for moduleList
-- ----------------------------
DROP TABLE IF EXISTS "moduleList";
CREATE TABLE "moduleList" (
  "moduleId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "moduleName" VARCHAR(4000),
  "isSystemDefine" integer
);

-- ----------------------------
-- Records of "moduleList"
-- ----------------------------
INSERT INTO "moduleList" VALUES (1, 'HSDPP任务清单', 1);
INSERT INTO "moduleList" VALUES (2, '前台功能清单、参数、权限', 1);
INSERT INTO "moduleList" VALUES (3, '监控规则', 1);
INSERT INTO "moduleList" VALUES (4, '个性化报表', 1);
INSERT INTO "moduleList" VALUES (5, '订阅任务', 1);
INSERT INTO "moduleList" VALUES (6, '组合树、维度', 1);
INSERT INTO "moduleList" VALUES (8, '指标、条件表达式', 1);

-- ----------------------------
-- Table structure for moduleObject
-- ----------------------------
DROP TABLE IF EXISTS "moduleObject";
CREATE TABLE "moduleObject" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "moduleName" VARCHAR(4000),
  "objectName" VARCHAR(4000),
  "objectType" INTEGER,
  "isSystemDefine" integer
);

-- ----------------------------
-- Records of "moduleObject"
-- ----------------------------
INSERT INTO "moduleObject" VALUES (81, 'HSDPP任务清单', 'TDPF_TASK_INFO', 1, 1);
INSERT INTO "moduleObject" VALUES (82, 'HSDPP任务清单', 'TDPF_TASKBUSIPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (83, 'HSDPP任务清单', 'TDPF_TASK_EXENO', 1, 1);
INSERT INTO "moduleObject" VALUES (84, 'HSDPP任务清单', 'TDPF_GLOBAL_PARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (85, '前台功能清单、参数、权限', 'TSYS_TRANS', 1, 1);
INSERT INTO "moduleObject" VALUES (86, '前台功能清单、参数、权限', 'TSYS_PARAMETER', 1, 1);
INSERT INTO "moduleObject" VALUES (87, '前台功能清单、参数、权限', 'TSYS_USER_RIGHT', 1, 1);
INSERT INTO "moduleObject" VALUES (88, '前台功能清单、参数、权限', 'TSYS_USER', 1, 1);
INSERT INTO "moduleObject" VALUES (89, '前台功能清单、参数、权限', 'TSYS_ROLE', 1, 1);
INSERT INTO "moduleObject" VALUES (90, '前台功能清单、参数、权限', 'TSYS_ROLE_RIGHT', 1, 1);
INSERT INTO "moduleObject" VALUES (91, '监控规则', 'TMONITORRESULTS', 1, 1);
INSERT INTO "moduleObject" VALUES (92, '监控规则', 'TMONITORRULES', 1, 1);
INSERT INTO "moduleObject" VALUES (93, '监控规则', 'TMONITORRULESCURRENTS', 1, 1);
INSERT INTO "moduleObject" VALUES (94, '监控规则', 'TMONITORRULEACCVALUESCURRENTS', 1, 1);
INSERT INTO "moduleObject" VALUES (95, '个性化报表', 'TREPORTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (96, '个性化报表', 'TREPORTRESULTS', 1, 1);
INSERT INTO "moduleObject" VALUES (97, '个性化报表', 'TREPORTSPECIALPARAM', 1, 1);
INSERT INTO "moduleObject" VALUES (98, '个性化报表', 'TSUBREPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (99, '个性化报表', 'TSUBRTPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (100, '个性化报表', 'TSUBRTINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (101, '个性化报表', 'TSQLSELTABLE', 1, 1);
INSERT INTO "moduleObject" VALUES (102, '个性化报表', 'TSUBRTINDEXPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (103, '订阅任务', 'TSSREPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (104, '订阅任务', 'TSSPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (105, '订阅任务', 'TSUBCRIBEINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (106, '组合树、维度', 'TPORTTREEDATA', 1, 1);
INSERT INTO "moduleObject" VALUES (107, '组合树、维度', 'TDIMDIVIDEDETAIL', 1, 1);
INSERT INTO "moduleObject" VALUES (108, '组合树、维度', 'TDIMINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (109, '组合树、维度', 'TDIMDIVIDEWAY', 1, 1);
INSERT INTO "moduleObject" VALUES (110, '自定义基准、利率及指数', 'TBENCHCOMPONENT', 1, 1);
INSERT INTO "moduleObject" VALUES (111, '自定义基准、利率及指数', 'TBENCHMARKINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (112, '自定义基准、利率及指数', 'TCUSTOMINDEXINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (113, '自定义基准、利率及指数', 'TCUSTOMINDEXPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (114, '自定义基准、利率及指数', 'TCUSTOMINTEREST', 1, 1);
INSERT INTO "moduleObject" VALUES (115, '自定义基准、利率及指数', 'TCUSTOMINTERESTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (116, '指标、条件表达式', 'TINDEXSETINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (117, '指标、条件表达式', 'TINDEXSETPARAM', 1, 1);
INSERT INTO "moduleObject" VALUES (118, '指标、条件表达式', 'TCONLISTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (119, '自定义视图', 'TSUBFUNCUSTOMVIEW', 1, 1);
INSERT INTO "moduleObject" VALUES (120, '自定义视图', 'TSUBFCVWPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (121, '自定义视图', 'TSUBFCVWINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (122, '自定义视图', 'TFUNCUSTOMVIEW', 1, 1);
INSERT INTO "moduleObject" VALUES (123, '自定义视图', 'TSUBFCVWREGIONINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (124, '自定义视图', 'TSUBFCVWREGION', 1, 1);

-- ----------------------------
-- Table structure for objectFunctionQuota
-- ----------------------------
DROP TABLE IF EXISTS "objectFunctionQuota";
CREATE TABLE "objectFunctionQuota" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "objectName" VARCHAR(4000),
  "objectType" INTEGER,
  "functionQuotaName" VARCHAR(4000),
  "functionQuotaType" INTEGER,
  "isSystemDefineMoudle" integer NOT NULL
);

-- ----------------------------
-- Records of "objectFunctionQuota"
-- ----------------------------
INSERT INTO "objectFunctionQuota" VALUES (1, '表1', 1, '功能1', 1, 1);
INSERT INTO "objectFunctionQuota" VALUES (2, '表2', 1, '功能1', 1, 1);
INSERT INTO "objectFunctionQuota" VALUES (3, '表2', 1, '功能2', 1, 0);

-- ----------------------------
-- Table structure for sqlite_sequence
-- ----------------------------
DROP TABLE IF EXISTS "sqlite_sequence";
CREATE TABLE "sqlite_sequence" (
  "name",
  "seq"
);

-- ----------------------------
-- Records of "sqlite_sequence"
-- ----------------------------
INSERT INTO "sqlite_sequence" VALUES ('backupFieldKey', 1226);
INSERT INTO "sqlite_sequence" VALUES ('functionQuotaList', 3);
INSERT INTO "sqlite_sequence" VALUES ('moduleList', 8);
INSERT INTO "sqlite_sequence" VALUES ('moduleObject', 124);
INSERT INTO "sqlite_sequence" VALUES ('objectFunctionQuota', 3);
INSERT INTO "sqlite_sequence" VALUES ('backupObjectNameList', 178);
INSERT INTO "sqlite_sequence" VALUES ('backupInformation', 7);

