/*
 Navicat Premium Data Transfer

 Source Server         : SQLite
 Source Server Type    : SQLite
 Source Server Version : 3017000
 Source Schema         : main

 Target Server Type    : SQLite
 Target Server Version : 3017000
 File Encoding         : 65001

 Date: 27/08/2019 16:44:33
*/

PRAGMA foreign_keys = false;

-- ----------------------------
-- Table structure for backupFieldKey
-- ----------------------------
DROP TABLE IF EXISTS "backupFieldKey";
CREATE TABLE "backupFieldKey" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "tableName" VARCHAR(4000),
  "fieldChosed" varchar(4000),
  "fieldType" text(4000),
  "isSystemDefine" integer,
  "modifier" VARCHAR(4000),
  "modificationTime" integer
);

-- ----------------------------
-- Records of "backupFieldKey"
-- ----------------------------
INSERT INTO "backupFieldKey" VALUES (256, 'TDPF_TASK_INFO', 'C_TASKID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (269, 'TDPF_TASKBUSIPARAMS', 'C_PARAMID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (281, 'TDPF_GLOBAL_PARAMS', 'C_GPARAMID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (282, 'TDPF_TASK_EXENO', 'C_TASKTAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (283, 'TDPF_TASK_EXENO', 'C_PRETASKTAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (284, 'tsys_trans', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (285, 'tsys_parameter', 'VC_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (286, 'tparameter', 'PARAM_CODE, REL_ORG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (287, 'tsys_user_right', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (288, 'tsys_user_right', 'SUB_TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (289, 'tsys_user_right', 'USER_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (290, 'tsys_user_right', 'BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (291, 'tsys_user_right', 'END_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (292, 'tsys_user_right', 'RIGHT_FLAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (293, 'tsys_user', 'USER_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (294, 'tsys_role', 'ROLE_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (295, 'tsys_role_right', 'TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (296, 'tsys_role_right', 'SUB_TRANS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (297, 'tsys_role_right', 'ROLE_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (298, 'tsys_role_right', 'BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (299, 'tsys_role_right', 'RIGHT_FLAG', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (300, 'tsys_role_right', 'END_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (301, 'TINDEXSETINDEXS', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (302, 'TINDEXSETINDEXS', 'VC_INDEXS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (303, 'TINDEXSETPARAM', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (304, 'TINDEXSETPARAM', 'VC_INDEXS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (305, 'TCONLISTINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (306, 'tmonitorresults', 'l_date', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (307, 'tmonitorresults', 'l_port_id', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (308, 'tmonitorresults', 'l_ruleid', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (309, 'tmonitorresults', 'vc_scode', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (310, 'TREPORTINFO', 'L_REPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (311, 'TREPORTSPECIALPARAM', 'l_reportid', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (312, 'TREPORTSPECIALPARAM', 'VC_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (313, 'TSUBREPORTS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (314, 'TSUBRTPARAMS', 'l_subreportid', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (315, 'TSUBRTPARAMS', 'VC_PARAMNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (316, 'TSUBRTINDEXS', 'l_subreportid', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (317, 'TSUBRTINDEXS', 'VC_DISPLAYNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (318, 'TSUBRTINDEXS', 'VC_INDEXSET_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (319, 'TSUBRTINDEXS', 'VC_INDEXS_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (320, 'TSQLSELTABLE', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (321, 'TSUBRTINDEXPARAMS', 'L_SUBREPORTID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (322, 'TSUBRTINDEXPARAMS', 'C_INDEXGUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (323, 'TSUBRTINDEXPARAMS', 'VC_PARAMNAME', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (324, 'TSSREPORTS', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (325, 'TSSPORTS', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (326, 'TSUBCRIBEINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (327, 'TPORTTREEDATA', 'L_NODE_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (328, 'tdimdividedetail', 'L_DDETAILSID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (329, 'TDIMINFO', 'C_GUID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (330, 'TDIMDIVIDEWAY', 'L_DIVIDEID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (331, 'TBENCHCOMPONENT', 'L_BENCH_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (332, 'TBENCHCOMPONENT', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (333, 'TBENCHCOMPONENT', 'L_BEGIN_DATE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (334, 'TBENCHMARKINFO', 'L_BENCH_ID', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (335, 'TCUSTOMINDEXINFO', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (336, 'TCUSTOMINDEXPARAMS', 'VC_INDEX_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (337, 'TCUSTOMINDEXPARAMS', 'VC_PARA_CODE', 2, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (339, 'TDPF_TASK_INFO', 'VC_CUSTOMTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (340, 'TDPF_TASK_INFO', 'C_TASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (341, 'TDPF_TASK_INFO', 'C_UPTASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (342, 'TDPF_TASK_INFO', 'VC_TASKNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (343, 'TDPF_TASK_INFO', 'VC_TASKDLL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (344, 'TDPF_TASK_INFO', 'C_STARTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (345, 'TDPF_TASK_INFO', 'C_EXETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (346, 'TDPF_TASK_INFO', 'L_EXENO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (347, 'TDPF_TASK_INFO', 'C_RUNSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (348, 'TDPF_TASK_INFO', 'L_PROGRESSVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (349, 'TDPF_TASK_INFO', 'VC_TASKEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (350, 'TDPF_TASK_INFO', 'VC_EXETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (351, 'TDPF_TASK_INFO', 'VC_BEGINTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (352, 'TDPF_TASK_INFO', 'VC_ENDTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (353, 'TDPF_TASK_INFO', 'VC_UPEXEDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (354, 'TDPF_TASK_INFO', 'L_TIMEINTERVAL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (355, 'TDPF_TASK_INFO', 'VC_WEEKDAYEXE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (356, 'TDPF_TASK_INFO', 'VC_MONTHWEEKEXE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (357, 'TDPF_TASK_INFO', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (358, 'TDPF_TASK_INFO', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (359, 'TDPF_TASK_INFO', 'VC_TASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (360, 'TDPF_TASKBUSIPARAMS', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (361, 'TDPF_TASKBUSIPARAMS', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (362, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (363, 'TDPF_TASKBUSIPARAMS', 'C_PARAMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (364, 'TDPF_TASKBUSIPARAMS', 'C_TASKID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (365, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (366, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (367, 'TDPF_TASKBUSIPARAMS', 'C_EDITSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (368, 'TDPF_TASKBUSIPARAMS', 'C_ISENCRYPT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (369, 'TDPF_TASKBUSIPARAMS', 'VC_PARAMEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (370, 'TDPF_TASKBUSIPARAMS', 'L_VALUETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (371, 'TDPF_TASKBUSIPARAMS', 'VC_VALUERANGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (372, 'TDPF_GLOBAL_PARAMS', 'C_GPARAMID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (373, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (374, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (375, 'TDPF_GLOBAL_PARAMS', 'C_EDITSTATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (376, 'TDPF_GLOBAL_PARAMS', 'C_ISENCRYPT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (377, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMEXPLAIN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (378, 'TDPF_GLOBAL_PARAMS', 'L_VALUETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (379, 'TDPF_GLOBAL_PARAMS', 'VC_VALUERANGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (380, 'TDPF_GLOBAL_PARAMS', 'VC_UPDATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (381, 'TDPF_GLOBAL_PARAMS', 'VC_UPDATETIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (382, 'TDPF_GLOBAL_PARAMS', 'VC_GPARAMALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (383, 'TDPF_TASK_EXENO', 'C_EXEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (384, 'TDPF_TASK_EXENO', 'C_TASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (385, 'TDPF_TASK_EXENO', 'C_PRETASKTAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (386, 'TINDEXSETINDEXS', 'C_ISADDBENCHHOLD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (387, 'TINDEXSETINDEXS', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (388, 'TINDEXSETINDEXS', 'VC_INDEXS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (389, 'TINDEXSETINDEXS', 'VC_INDEXS_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (390, 'TINDEXSETINDEXS', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (391, 'TINDEXSETINDEXS', 'L_INDEXS_DIM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (392, 'TINDEXSETINDEXS', 'L_INDEXS_AGGREGATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (393, 'TINDEXSETINDEXS', 'VC_WEIGHT_FIELD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (394, 'TINDEXSETINDEXS', 'L_INDEXVALUE_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (395, 'TINDEXSETINDEXS', 'L_INDEXS_EXTFLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (396, 'TINDEXSETINDEXS', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (397, 'TINDEXSETINDEXS', 'L_MODULE_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (398, 'TINDEXSETINDEXS', 'L_INDEXVALUELEN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (399, 'TINDEXSETINDEXS', 'VC_ISSHOW_FLAG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (400, 'TINDEXSETINDEXS', 'L_RESULTUNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (401, 'TINDEXSETINDEXS', 'L_RESULTPRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (402, 'TINDEXSETINDEXS', 'L_IS_STORAGE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (403, 'TINDEXSETINDEXS', 'VC_DEFAULTSHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (404, 'TINDEXSETINDEXS', 'VC_INDEX_PARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (405, 'TINDEXSETINDEXS', 'VC_INDEX_VIEWPARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (406, 'TINDEXSETINDEXS', 'VC_DEFAULTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (407, 'TINDEXSETINDEXS', 'RISK_FUNCTION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (408, 'TINDEXSETPARAM', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (409, 'TINDEXSETPARAM', 'VC_PARAM_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (410, 'TINDEXSETPARAM', 'VC_PARAM_CHNNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (411, 'TINDEXSETPARAM', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (412, 'TINDEXSETPARAM', 'VC_PARAM_DEAFTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (413, 'TINDEXSETPARAM', 'L_UNIT_INDEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (414, 'TINDEXSETPARAM', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (415, 'TINDEXSETPARAM', 'VC_XTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (416, 'TINDEXSETPARAM', 'VC_CONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (417, 'TINDEXSETPARAM', 'VC_UNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (418, 'TINDEXSETPARAM', 'VC_MIXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (419, 'TINDEXSETPARAM', 'VC_MAXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (420, 'TINDEXSETPARAM', 'L_PRECISION', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (421, 'TINDEXSETPARAM', 'VC_PARAMDYNAMIC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (422, 'TCONLISTINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (423, 'TCONLISTINFO', 'C_CONGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (424, 'TCONLISTINFO', 'L_NO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (425, 'TCONLISTINFO', 'VC_INDEXCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (426, 'TCONLISTINFO', 'L_RELATIONEXP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (427, 'TCONLISTINFO', 'VC_INDEXVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (428, 'TCONLISTINFO', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (429, 'TCONLISTINFO', 'VC_INDEXVALUENAMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (430, 'TCONLISTINFO', 'VC_PARAMVALUENAMES', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (431, 'TCONLISTINFO', 'VC_GROUPGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (432, 'TCONLISTINFO', 'L_CONTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (433, 'TREPORTINFO', 'L_CALC_PORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (434, 'TREPORTINFO', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (435, 'TREPORTINFO', 'VC_REPORTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (436, 'TREPORTINFO', 'VC_REPORTDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (437, 'TREPORTINFO', 'C_REPORTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (438, 'TREPORTINFO', 'VC_CREATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (439, 'TREPORTINFO', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (440, 'TREPORTINFO', 'VC_CHECKCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (441, 'TREPORTINFO', 'L_DATEFREQUENCY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (442, 'TREPORTINFO', 'L_SHOWPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (443, 'TREPORTINFO', 'L_SHOWBECHE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (444, 'TREPORTINFO', 'L_SHOWBENCH', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (445, 'TREPORTINFO', 'L_REPORT_TEMPLET', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (446, 'TREPORTINFO', 'VC_REPORT_CNTDEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (447, 'TREPORTINFO', 'VC_EXPORT_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (448, 'TREPORTSPECIALPARAM', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (449, 'TREPORTSPECIALPARAM', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (450, 'TREPORTSPECIALPARAM', 'VC_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (451, 'TREPORTSPECIALPARAM', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (452, 'TREPORTSPECIALPARAM', 'VC_DEFAULTVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (453, 'TREPORTSPECIALPARAM', 'VC_FIELDCONFIG', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (454, 'TREPORTSPECIALPARAM', 'VC_XTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (455, 'TREPORTSPECIALPARAM', 'L_DICTNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (456, 'TREPORTSPECIALPARAM', 'VC_CONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (457, 'TREPORTSPECIALPARAM', 'VC_UNIT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (458, 'TREPORTSPECIALPARAM', 'L_ALLOWBLANK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (459, 'TREPORTSPECIALPARAM', 'L_SHOW', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (460, 'TREPORTSPECIALPARAM', 'L_MULTIPLE_SELECT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (461, 'TREPORTSPECIALPARAM', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (462, 'TSUBREPORTS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (463, 'TSUBREPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (464, 'TSUBREPORTS', 'VC_SUBREPORTNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (465, 'TSUBREPORTS', 'VC_SUBREPORTENNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (466, 'TSUBREPORTS', 'VC_SUBREPORTDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (467, 'TSUBREPORTS', 'L_DATEFREQUENCY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (468, 'TSUBREPORTS', 'L_SUBREPORTWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (469, 'TSUBREPORTS', 'VC_SQLGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (470, 'TSUBREPORTS', 'L_SUBREPORTNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (471, 'TSUBREPORTS', 'VC_DIMGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (472, 'TSUBREPORTS', 'L_ACTIVE_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (473, 'TSUBREPORTS', 'L_MAPTYPE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (474, 'TSUBREPORTS', 'VC_DEFINESQL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (475, 'TSUBREPORTS', 'L_SQLTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (476, 'TSUBRTPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (477, 'TSUBRTPARAMS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (478, 'TSUBRTPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (479, 'TSUBRTPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (480, 'TSUBRTINDEXS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (481, 'TSUBRTINDEXS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (482, 'TSUBRTINDEXS', 'L_INDEXNO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (483, 'TSUBRTINDEXS', 'VC_DISPLAYNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (484, 'TSUBRTINDEXS', 'L_INDEXSEQ', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (485, 'TSUBRTINDEXS', 'VC_INDEXSET_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (486, 'TSUBRTINDEXS', 'VC_INDEXS_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (487, 'TSQLSELTABLE', 'VC_SQLCNTEX', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (488, 'TSQLSELTABLE', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (489, 'TSQLSELTABLE', 'VC_SQLNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (490, 'TSQLSELTABLE', 'VC_SQLCNT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (491, 'TSQLSELTABLE', 'VC_SQLDESP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (492, 'TSQLSELTABLE', 'L_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (493, 'TSQLSELTABLE', 'L_CALCWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (494, 'TSQLSELTABLE', 'VC_FUNCNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (495, 'TSQLSELTABLE', 'L_MANCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (496, 'TSUBRTINDEXPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (497, 'TSUBRTINDEXPARAMS', 'L_SUBREPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (498, 'TSUBRTINDEXPARAMS', 'C_INDEXGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (499, 'TSUBRTINDEXPARAMS', 'VC_PARAMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (500, 'TSUBRTINDEXPARAMS', 'VC_PARAMVALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (501, 'TSSREPORTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (502, 'TSSREPORTS', 'C_SSGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (503, 'TSSREPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (504, 'TSSREPORTS', 'VC_TRANSPARAM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (505, 'TSSPORTS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (506, 'TSSPORTS', 'C_SSGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (507, 'TSSPORTS', 'L_PORTTREE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (508, 'TSSPORTS', 'L_REPORTID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (509, 'TSUBCRIBEINFO', 'C_REMOVEDELISTPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (510, 'TSUBCRIBEINFO', 'VC_MAILTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (511, 'TSUBCRIBEINFO', 'VC_FILENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (512, 'TSUBCRIBEINFO', 'VC_CCMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (513, 'TSUBCRIBEINFO', 'ISFTPUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (514, 'TSUBCRIBEINFO', 'L_EDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (515, 'TSUBCRIBEINFO', 'DATEFROM', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (516, 'TSUBCRIBEINFO', 'ISCALCHIS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (517, 'TSUBCRIBEINFO', 'VC_TASKNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (518, 'TSUBCRIBEINFO', 'REPCONCURRENCE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (519, 'TSUBCRIBEINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (520, 'TSUBCRIBEINFO', 'VC_RECMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (521, 'TSUBCRIBEINFO', 'C_RECGROUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (522, 'TSUBCRIBEINFO', 'C_ISRECGROUP', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (523, 'TSUBCRIBEINFO', 'L_CALCDUR', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (524, 'TSUBCRIBEINFO', 'D_UPCALCDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (525, 'TSUBCRIBEINFO', 'C_ONOFF', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (526, 'TSUBCRIBEINFO', 'C_SENDMAIL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (527, 'TSUBCRIBEINFO', 'L_RFILEFORMAT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (528, 'TSUBCRIBEINFO', 'VC_RBEGINDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (529, 'TSUBCRIBEINFO', 'VC_REMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (530, 'TSUBCRIBEINFO', 'VC_MONIFYMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (531, 'TSUBCRIBEINFO', 'D_MONIFYTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (532, 'TSUBCRIBEINFO', 'VC_CREATEMAN', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (533, 'TSUBCRIBEINFO', 'D_CREATEDATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (534, 'TSUBCRIBEINFO', 'VC_MAILTITLE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (535, 'TSUBCRIBEINFO', 'VC_MAILCONTENT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (536, 'TSUBCRIBEINFO', 'L_PRIORITY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (537, 'TSUBCRIBEINFO', 'L_DATETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (538, 'TSUBCRIBEINFO', 'L_DELAYDAYS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (539, 'TSUBCRIBEINFO', 'L_EXPORT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (540, 'TSUBCRIBEINFO', 'SENDREPORTTYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (541, 'TSUBCRIBEINFO', 'ISPACK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (542, 'TSUBCRIBEINFO', 'VC_TRIGGERTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (543, 'TSUBCRIBEINFO', 'D_LASTTIME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (544, 'TSUBCRIBEINFO', 'ISREMINDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (545, 'TPORTTREEDATA', 'L_PEER_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (546, 'TPORTTREEDATA', 'L_NODE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (547, 'TPORTTREEDATA', 'VC_NODE_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (548, 'TPORTTREEDATA', 'L_PARENT_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (549, 'TPORTTREEDATA', 'L_CASHFLOW_STRATEGY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (550, 'TPORTTREEDATA', 'L_DIVIDEND_STRATEGY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (551, 'TPORTTREEDATA', 'L_TREE_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (552, 'TPORTTREEDATA', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (553, 'TPORTTREEDATA', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (554, 'TPORTTREEDATA', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (555, 'TPORTTREEDATA', 'VC_NODE_ALIASNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (556, 'TPORTTREEDATA', 'L_CREATE_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (557, 'TPORTTREEDATA', 'L_MARKET_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (558, 'TPORTTREEDATA', 'L_INNER_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (559, 'TPORTTREEDATA', 'L_DEPART_BENCHMARK', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (560, 'TPORTTREEDATA', 'C_DIM_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (561, 'TPORTTREEDATA', 'VC_PEER_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (562, 'TDIMINFO', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (563, 'TDIMINFO', 'C_PGUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (564, 'TDIMINFO', 'L_DIMTREEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (565, 'TDIMINFO', 'VC_DIMNAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (566, 'TDIMINFO', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (567, 'TDIMINFO', 'VC_DIVIDENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (568, 'TDIMINFO', 'L_DDETAILSID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (569, 'TDIMINFO', 'L_LEVEL', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (570, 'TDIMINFO', 'L_SHOWWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (571, 'TDIMINFO', 'L_READONLY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (572, 'TDIMINFO', 'L_CLASS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (573, 'TDIMINFO', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (574, 'TDIMINFO', 'L_DIMCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (575, 'TDIMINFO', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (576, 'TDIMINFO', 'VC_FUNCEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (577, 'TDIMDIVIDEWAY', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (578, 'TDIMDIVIDEWAY', 'VC_DIMDIVIDENAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (579, 'TDIMDIVIDEWAY', 'L_DIVIDETYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (580, 'TDIMDIVIDEWAY', 'L_DIMFUNCID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (581, 'TDIMDIVIDEWAY', 'L_READONLY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (582, 'TDIMDIVIDEWAY', 'L_CLASS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (583, 'TDIMDIVIDEWAY', 'L_ORDER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (584, 'TDIMDIVIDEWAY', 'VC_CONSEXPS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (585, 'TDIMDIVIDEWAY', 'L_DIMCODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (586, 'TBENCHCOMPONENT', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (587, 'TBENCHCOMPONENT', 'L_BENCH_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (588, 'TBENCHCOMPONENT', 'L_DIM_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (589, 'TBENCHCOMPONENT', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (590, 'TBENCHCOMPONENT', 'L_BEGIN_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (591, 'TBENCHCOMPONENT', 'EN_WEIGHT', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (592, 'TBENCHCOMPONENT', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (593, 'TBENCHCOMPONENT', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (594, 'TBENCHMARKINFO', 'RATEADD', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (595, 'TBENCHMARKINFO', 'RATEADDCALCWAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (596, 'TBENCHMARKINFO', 'L_BENCH_ID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (597, 'TBENCHMARKINFO', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (598, 'TBENCHMARKINFO', 'VC_CALCWEIGHT_WAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (599, 'TBENCHMARKINFO', 'VC_ACCUMULATE_WAY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (600, 'TBENCHMARKINFO', 'L_DIVIDEID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (601, 'TBENCHMARKINFO', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (602, 'TBENCHMARKINFO', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (603, 'TBENCHMARKINFO', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (604, 'TBENCHMARKINFO', 'C_CATEGORY', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (605, 'TCUSTOMINDEXINFO', 'L_ISSYS', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (606, 'TCUSTOMINDEXINFO', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (607, 'TCUSTOMINDEXINFO', 'VC_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (608, 'TCUSTOMINDEXINFO', 'C_NIGHT_CALC', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (609, 'TCUSTOMINDEXINFO', 'VC_INDEX_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (610, 'TCUSTOMINDEXINFO', 'L_SAMPWEIGHT_TYPE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (611, 'TCUSTOMINDEXINFO', 'VC_MEMO', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (612, 'TCUSTOMINDEXINFO', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (613, 'TCUSTOMINDEXINFO', 'VC_MODIFIER', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (614, 'TCUSTOMINDEXPARAMS', 'C_GUID', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (615, 'TCUSTOMINDEXPARAMS', 'VC_INDEX_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (616, 'TCUSTOMINDEXPARAMS', 'VC_PARA_CODE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (617, 'TCUSTOMINDEXPARAMS', 'VC_PARA_NAME', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (618, 'TCUSTOMINDEXPARAMS', 'VC_PARA_VALUE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (619, 'TCUSTOMINDEXPARAMS', 'L_MODI_DATE', 1, 1, NULL, NULL);
INSERT INTO "backupFieldKey" VALUES (620, 'TCUSTOMINDEXPARAMS', 'VC_MODIFIER', 1, 1, NULL, NULL);

-- ----------------------------
-- Table structure for backupInformation
-- ----------------------------
DROP TABLE IF EXISTS "backupInformation";
CREATE TABLE "backupInformation" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "backupVersion" integer,
  "backupTime" text,
  "beginTime" integer,
  "endTime" integer,
  "hasContrast" integer
);

-- ----------------------------
-- Table structure for backupObjectNameList
-- ----------------------------
DROP TABLE IF EXISTS "backupObjectNameList";
CREATE TABLE "backupObjectNameList" (
  "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "backupVersion" INTEGER,
  "objectName" text(4000),
  "backupObjectName" integer(4000),
  "ObjectType" INTEGER
);

-- ----------------------------
-- Table structure for functionQuotaList
-- ----------------------------
DROP TABLE IF EXISTS "functionQuotaList";
CREATE TABLE "functionQuotaList" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "functionQuotaName" VARCHAR(4000),
  "functionQuotaType" INTEGER
);

-- ----------------------------
-- Records of "functionQuotaList"
-- ----------------------------
INSERT INTO "functionQuotaList" VALUES (1, '功能1', 1);
INSERT INTO "functionQuotaList" VALUES (2, '功能2', 1);
INSERT INTO "functionQuotaList" VALUES (3, '指标1', 2);

-- ----------------------------
-- Table structure for moduleList
-- ----------------------------
DROP TABLE IF EXISTS "moduleList";
CREATE TABLE "moduleList" (
  "moduleId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "moduleName" VARCHAR(4000),
  "isSystemDefine" integer
);

-- ----------------------------
-- Records of "moduleList"
-- ----------------------------
INSERT INTO "moduleList" VALUES (1, 'HSDPP任务清单', 1);
INSERT INTO "moduleList" VALUES (2, '前台功能清单、参数、权限', 1);
INSERT INTO "moduleList" VALUES (3, '监控规则', 1);
INSERT INTO "moduleList" VALUES (4, '个性化报表', 1);
INSERT INTO "moduleList" VALUES (5, '订阅任务', 1);
INSERT INTO "moduleList" VALUES (6, '组合树、维度', 1);
INSERT INTO "moduleList" VALUES (8, '指标、条件表达式', 1);

-- ----------------------------
-- Table structure for moduleObject
-- ----------------------------
DROP TABLE IF EXISTS "moduleObject";
CREATE TABLE "moduleObject" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "moduleName" VARCHAR(4000),
  "objectName" VARCHAR(4000),
  "objectType" INTEGER,
  "isSystemDefine" integer
);

-- ----------------------------
-- Records of "moduleObject"
-- ----------------------------
INSERT INTO "moduleObject" VALUES (81, 'HSDPP任务清单', 'tdpf_task_info', 1, 1);
INSERT INTO "moduleObject" VALUES (82, 'HSDPP任务清单', 'tdpf_taskbusiparams', 1, 1);
INSERT INTO "moduleObject" VALUES (83, 'HSDPP任务清单', 'tdpf_task_exeno', 1, 1);
INSERT INTO "moduleObject" VALUES (84, 'HSDPP任务清单', 'tdpf_global_params', 1, 1);
INSERT INTO "moduleObject" VALUES (85, '前台功能清单、参数、权限', 'tsys_trans', 1, 1);
INSERT INTO "moduleObject" VALUES (86, '前台功能清单、参数、权限', 'tsys_parameter', 1, 1);
INSERT INTO "moduleObject" VALUES (87, '前台功能清单、参数、权限', 'tsys_user_right', 1, 1);
INSERT INTO "moduleObject" VALUES (88, '前台功能清单、参数、权限', 'tsys_user', 1, 1);
INSERT INTO "moduleObject" VALUES (89, '前台功能清单、参数、权限', 'tsys_role', 1, 1);
INSERT INTO "moduleObject" VALUES (90, '前台功能清单、参数、权限', 'tsys_role_right', 1, 1);
INSERT INTO "moduleObject" VALUES (91, '监控规则', 'tmonitorresults', 1, 1);
INSERT INTO "moduleObject" VALUES (92, '监控规则', 'tmonitorrules', 1, 1);
INSERT INTO "moduleObject" VALUES (93, '监控规则', 'TMONITORRULESCURRENTS', 1, 1);
INSERT INTO "moduleObject" VALUES (94, '监控规则', 'tmonitorruleaccvaluescurrents', 1, 1);
INSERT INTO "moduleObject" VALUES (95, '个性化报表', 'TREPORTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (96, '个性化报表', 'TREPORTRESULTS', 1, 1);
INSERT INTO "moduleObject" VALUES (97, '个性化报表', 'TREPORTSPECIALPARAM', 1, 1);
INSERT INTO "moduleObject" VALUES (98, '个性化报表', 'TSUBREPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (99, '个性化报表', 'TSUBRTPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (100, '个性化报表', 'TSUBRTINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (101, '个性化报表', 'TSQLSELTABLE', 1, 1);
INSERT INTO "moduleObject" VALUES (102, '个性化报表', 'TSUBRTINDEXPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (103, '订阅任务', 'TSSREPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (104, '订阅任务', 'TSSPORTS', 1, 1);
INSERT INTO "moduleObject" VALUES (105, '订阅任务', 'TSUBCRIBEINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (106, '组合树、维度', 'TPORTTREEDATA', 1, 1);
INSERT INTO "moduleObject" VALUES (107, '组合树、维度', 'tdimdividedetail', 1, 1);
INSERT INTO "moduleObject" VALUES (108, '组合树、维度', 'TDIMINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (109, '组合树、维度', 'TDIMDIVIDEWAY', 1, 1);
INSERT INTO "moduleObject" VALUES (110, '自定义基准、利率及指数', 'TBENCHCOMPONENT', 1, 1);
INSERT INTO "moduleObject" VALUES (111, '自定义基准、利率及指数', 'TBENCHMARKINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (112, '自定义基准、利率及指数', 'TCUSTOMINDEXINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (113, '自定义基准、利率及指数', 'TCUSTOMINDEXPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (114, '自定义基准、利率及指数', 'TCUSTOMINTEREST', 1, 1);
INSERT INTO "moduleObject" VALUES (115, '自定义基准、利率及指数', 'TCUSTOMINTERESTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (116, '指标、条件表达式', 'TINDEXSETINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (117, '指标、条件表达式', 'TINDEXSETPARAM', 1, 1);
INSERT INTO "moduleObject" VALUES (118, '指标、条件表达式', 'TCONLISTINFO', 1, 1);
INSERT INTO "moduleObject" VALUES (119, '自定义视图', 'TSUBFUNCUSTOMVIEW', 1, 1);
INSERT INTO "moduleObject" VALUES (120, '自定义视图', 'TSUBFCVWPARAMS', 1, 1);
INSERT INTO "moduleObject" VALUES (121, '自定义视图', 'TSUBFCVWINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (122, '自定义视图', 'TFUNCUSTOMVIEW', 1, 1);
INSERT INTO "moduleObject" VALUES (123, '自定义视图', 'TSUBFCVWREGIONINDEXS', 1, 1);
INSERT INTO "moduleObject" VALUES (124, '自定义视图', 'TSUBFCVWREGION', 1, 1);

-- ----------------------------
-- Table structure for objectFunctionQuota
-- ----------------------------
DROP TABLE IF EXISTS "objectFunctionQuota";
CREATE TABLE "objectFunctionQuota" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "objectName" VARCHAR(4000),
  "objectType" INTEGER,
  "functionQuotaName" VARCHAR(4000),
  "functionQuotaType" INTEGER,
  "isSystemDefineMoudle" integer NOT NULL
);

-- ----------------------------
-- Records of "objectFunctionQuota"
-- ----------------------------
INSERT INTO "objectFunctionQuota" VALUES (1, '表1', 1, '功能1', 1, 1);
INSERT INTO "objectFunctionQuota" VALUES (2, '表2', 1, '功能1', 1, 1);
INSERT INTO "objectFunctionQuota" VALUES (3, '表2', 1, '功能2', 1, 0);

